update public.jobs set status='archived' where status='published';
insert into public.jobs (title,dept,location,type,description,status,posted_at) values
('HR Manager','Admin','Amlabad, Eastern Jharia, Jharkhand','Full-time','Oversee recruitment, statutory compliance, payroll, employee relations and camp administration for the colliery. Requirements: MBA (HR) or PGDM in Personnel Management; 2–3 years HR experience (mining / construction / manufacturing preferred); fluent in Hindi and English.','published','2026-07-06'),
('Company Secretary (CS)','Admin','Amlabad, Eastern Jharia, Jharkhand','Full-time','Handle ROC compliance, board meetings, statutory records and corporate agreements. Requirements: Qualified Company Secretary (ICSI); experience with corporate governance and Companies Act compliance.','published','2026-07-06'),
('Safety Incharge','Mining','Amlabad, Eastern Jharia, Jharkhand','Full-time','Lead safety operations — inspections, accident investigation and safety-management plans across working districts. Requirements: B.Tech / Diploma in Mining Engineering; valid First or Second Class Manager''s Certificate of Competency from DGMS (mandatory); 5–8 years mining experience with 2+ years in safety.','published','2026-07-06'),
('Store Manager (Mining Stores)','Admin','Amlabad, Eastern Jharia, Jharkhand','Full-time','Manage inventory of machinery spares, lubricants, diesel and consumables; prevent material shortages and maintain stock discipline. Requirements: Graduate (B.Com / B.Sc) or Diploma in Material Management; 7–10 years store-management experience (mining / heavy engineering preferred); MS Excel proficiency.','published','2026-07-06'),
('Mechanical Foreman','Mechanical','Amlabad, Eastern Jharia, Jharkhand','Full-time','Supervise mechanical maintenance, equipment repairs and breakdown troubleshooting; maintain statutory logbooks. Requirements: Diploma in Mechanical Engineering or ITI (Fitter); valid Foreman''s Certificate (Mechanical) from DGMS (mandatory); 5 years coal-mining machinery experience; hydraulics and pump knowledge.','published','2026-07-06'),
('Assistant Colliery Manager (Underground)','Mining','Amlabad, Eastern Jharia, Jharkhand','Full-time','Exercise statutory supervision over underground operations — shift management, safety compliance and emergency response. Requirements: B.Tech / Diploma in Mining Engineering; valid Second Class Manager''s Certificate of Competency (Coal) from DGMS (mandatory); valid Gas Testing and First-Aid certificates; 3–5 years underground coal-mining experience.','published','2026-07-06'),
('Colliery Engineer (Mechanical)','Mechanical','Amlabad, Eastern Jharia, Jharkhand','Full-time','Oversee installation and maintenance of underground and surface machinery, ensure DGMS compliance and conduct safety inspections. Requirements: B.Tech / Diploma in Mechanical Engineering; Engineer''s Certificate of Competency (Mechanical) for coal mines preferred; 5–8 years underground coal-mine experience; winder operations and dewatering systems knowledge.','published','2026-07-06'),
('Mining Engineer (Underground)','Mining','Amlabad, Eastern Jharia, Jharkhand','Full-time','Lead underground extraction and development, supervise operations, manage shift rostering and coordinate with planning. Requirements: B.Tech / Diploma in Mining Engineering; valid First or Second Class Manager''s Certificate of Competency; minimum 3 years underground coal-mining experience; experience in gassy or fire-prone conditions preferred.','published','2026-07-06'),
('Ventilation Officer','Mining','Amlabad, Eastern Jharia, Jharkhand','Full-time','Plan, monitor and maintain the mine ventilation system — air-quantity and quality surveys, methane and gas monitoring, ventilation planning, and compliance with the ventilation provisions of the Coal Mines Regulations 2017. Requirements: B.Tech / Diploma in Mining Engineering; valid Gas Testing Certificate; sound knowledge of mine ventilation and methane management; underground coal-mining experience preferred.','published','2026-07-06');
