begin;
-- retire the auto-mistitled row (cir_26_… was parsed as 'Circular 26'; it is Circular 03 of 2026)
delete from regulations where slug = 'dgms-tech-circular-26-of-2026-30-06-2026';

insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('dgms-tech-circular-03-2026-dust-suppression-additives', 'DGMS (Tech) Circular 03 of 2026 — Standard properties of chemical additives for dust suppression in coal mines', 'dgms_circular', 'Addressed to the owner, agent and manager of all coal mines and to manufacturers. It modifies Para 2(i) of DGMS Circular (Approval) No. 06 of 24 February 2015 so that the standard properties of chemical additives used as dust suppressants may be tested at other Government laboratories and test houses — not only at the four institutions named earlier (National Chemical Laboratory Pune, Industrial Toxicology Research Centre Lucknow, Indian School of Mines Dhanbad and CIMFR Dhanbad). The aim is to keep toxic and hazardous chemicals out of dust-suppression materials.', 'DGMS/S&T/Tech.Cir/(Approval) No. 03', 'DGMS', '2026-06-29', 'in_force', null, 'https://www.dgms.gov.in/writereaddata/UploadFile/cir_26_30062026.pdf', 'cir_26_30062026.pdf', 3, 230, true, false, 171, 'https://docs.mangalamcoal.com/regs/dgms-tech-circular-03-2026-dust-suppression-additives.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('dgms-tech-circular-04-2026-system-capacitive-current', 'DGMS (Tech) Circular 04 of 2026 — System capacitive current in restricted neutral power supply in mines', 'dgms_circular', 'Addressed to owners, agents and managers of all mines. Citing a rising trend of electrical accidents — seven lives lost and four serious injuries in 2025 alone — DGMS requires the system capacitive current to be taken into account in restricted-neutral power-supply systems, and calls for a review of electrical safety management alongside strict compliance with Regulation 103(1) of the CEA (Safety and Electric Supply) Regulations, 2023.', 'DGMS (Tech) Circular No. 04 of 2026', 'DGMS', '2026-07-14', 'in_force', null, 'https://www.dgms.gov.in/writereaddata/UploadFile/CircularTechnical2026_16072026.pdf', 'CircularTechnical2026_16072026.pdf', 3, 230, true, false, 395, 'https://docs.mangalamcoal.com/regs/dgms-tech-circular-04-2026-system-capacitive-current.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-571-2026-rescue-station-equipment', 'G.S.R. 571(E) — Apparatus and equipment to be maintained at rescue stations and rescue rooms', 'dgms_notification', 'Specifies, under rule 131(1) of the OSH&WC (Central) Rules 2026, the apparatus and equipment that must be provided and kept ready for immediate use at a rescue station and rescue room — including breathing apparatus, absorbent charges, resuscitating apparatus, testing devices and flame safety lamps, with minimum quantities for each.', 'G.S.R. 571(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GA_4_16072026.pdf', 'GA_4_16072026.pdf', 2, 320, true, false, 320, 'https://docs.mangalamcoal.com/regs/gsr-571-2026-rescue-station-equipment.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-572-2026-belowground-entrance-rescue-equipment', 'G.S.R. 572(E) — Rescue apparatus at the entrance of a belowground mine with no rescue room', 'dgms_notification', 'Specifies, under rule 131(2) of the OSH&WC (Central) Rules 2026, the apparatus and equipment to be provided and maintained at the entrance of a belowground mine where no rescue room is located.', 'G.S.R. 572(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification07_16072026.pdf', 'GazetteNotification07_16072026.pdf', 2, 320, true, false, 196, 'https://docs.mangalamcoal.com/regs/gsr-572-2026-belowground-entrance-rescue-equipment.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-573-2026-breathing-apparatus-testing', 'G.S.R. 573(E) — Procedure for testing breathing apparatus, flow meters and oxygen purity', 'dgms_notification', 'Lays down, under rule 131(5) of the OSH&WC (Central) Rules 2026, the procedure for testing breathing apparatus and flow meters, and for checking the purity of oxygen used in breathing apparatus.', 'G.S.R. 573(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GA_3_16072026.pdf', 'GA_3_16072026.pdf', 2, 320, true, false, 192, 'https://docs.mangalamcoal.com/regs/gsr-573-2026-breathing-apparatus-testing.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-574-2026-rescue-apparatus-accident-reporting', 'G.S.R. 574(E) — Format for reporting accidents involving rescue apparatus', 'dgms_notification', 'Prescribes the format for reporting accidents involving rescue apparatus in mines, rescue stations or rescue rooms, under the OSH&WC (Central) Rules 2026.', 'G.S.R. 574(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GA_2_16072026.pdf', 'GA_2_16072026.pdf', 2, 320, true, false, 201, 'https://docs.mangalamcoal.com/regs/gsr-574-2026-rescue-apparatus-accident-reporting.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-575-2026-rescue-team-signals', 'G.S.R. 575(E) — Code of signals for rescue team communication on breathing apparatus', 'dgms_notification', 'Specifies, under rule 152(3) of the OSH&WC (Central) Rules 2026, the code of signals rescue-trained persons must use to communicate while wearing breathing apparatus in belowground mines.', 'G.S.R. 575(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GA_1_16072026.pdf', 'GA_1_16072026.pdf', 2, 320, true, false, 183, 'https://docs.mangalamcoal.com/regs/gsr-575-2026-rescue-team-signals.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-576-2026-initial-rescue-training-courses', 'G.S.R. 576(E) — Courses of instruction and practice for initial training in rescue and recovery work', 'dgms_notification', 'Sets out the syllabus of instruction and practice for initial training in rescue and recovery work — including rope rescue using specified equipment — under the OSH&WC (Central) Rules 2026.', 'G.S.R. 576(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GA_5_16072026.pdf', 'GA_5_16072026.pdf', 2, 320, true, false, 686, 'https://docs.mangalamcoal.com/regs/gsr-576-2026-initial-rescue-training-courses.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-577-2026-rescue-trained-persons-courses', 'G.S.R. 577(E) — Courses of instruction and practice for rescue-trained persons', 'dgms_notification', 'Sets out the continuing courses of instruction and practice required for persons already rescue-trained, under the OSH&WC (Central) Rules 2026.', 'G.S.R. 577(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification03_16072026.pdf', 'GazetteNotification03_16072026.pdf', 2, 320, true, false, 179, 'https://docs.mangalamcoal.com/regs/gsr-577-2026-rescue-trained-persons-courses.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-578-2026-rescue-trainee-medical-standard', 'G.S.R. 578(E) — Standard of medical examination for persons selected for rescue and recovery training', 'dgms_notification', 'Specifies, under clause (iii) of rule 140 of the OSH&WC (Central) Rules 2026, the standard of medical examination for persons selected to undergo training in rescue and recovery work, together with the format of the medical record.', 'G.S.R. 578(E)', 'DGMS', '2026-07-01', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification04_16072026.pdf', 'GazetteNotification04_16072026.pdf', 2, 320, true, false, 791, 'https://docs.mangalamcoal.com/regs/gsr-578-2026-rescue-trainee-medical-standard.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-603-2026-periodical-medical-exam-notice', 'G.S.R. 603(E) — Form of notice of periodical medical examination', 'dgms_notification', 'Prescribes, under rule 111(2) of the OSH&WC (Central) Rules 2026, the form of the notice of periodical medical examination that a manager must give to the person to be examined; the notice is also sent to the examining authority.', 'G.S.R. 603(E)', 'DGMS', '2026-07-07', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification02_16072026.pdf', 'GazetteNotification02_16072026.pdf', 2, 320, true, false, 261, 'https://docs.mangalamcoal.com/regs/gsr-603-2026-periodical-medical-exam-notice.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-604-2026-second-medical-exam-notice', 'G.S.R. 604(E) — Form of second notice of medical examination', 'dgms_notification', 'Prescribes, under rule 111(4) of the OSH&WC (Central) Rules 2026, the form of the second notice of medical examination a manager must issue where a person has failed to attend the examination without reasonable cause.', 'G.S.R. 604(E)', 'DGMS', '2026-07-07', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification06_16072026.pdf', 'GazetteNotification06_16072026.pdf', 2, 320, true, false, 259, 'https://docs.mangalamcoal.com/regs/gsr-604-2026-second-medical-exam-notice.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('gsr-605-2026-initial-medical-exam-notice', 'G.S.R. 605(E) — Form of notice of initial medical examination', 'dgms_notification', 'Prescribes, under rule 111(1) of the OSH&WC (Central) Rules 2026, the form of the notice of initial medical examination that an employer must give to the person to be examined.', 'G.S.R. 605(E)', 'DGMS', '2026-07-07', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions (Central) Rules, 2026.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification09_16072026.pdf', 'GazetteNotification09_16072026.pdf', 2, 320, true, false, 271, 'https://docs.mangalamcoal.com/regs/gsr-605-2026-initial-medical-exam-notice.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('so-2490-2026-composition-of-offences-officers', 'S.O. 2490(E) — Officers notified for composition of offences in mines', 'dgms_notification', 'Under section 114(1) of the OSH&WC Code 2020, the Central Government notifies the officers empowered to compound offences in mines, with the jurisdiction of each.', 'S.O. 2490(E)', 'Ministry of Labour & Employment', '2026-05-13', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions Code, 2020.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification01_16072026.pdf', 'GazetteNotification01_16072026.pdf', 2, 320, true, false, 673, 'https://docs.mangalamcoal.com/regs/so-2490-2026-composition-of-offences-officers.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('so-2504-2026-penalty-imposing-officers', 'S.O. 2504(E) — Officers appointed to impose penalties under the OSH&WC Code in mines', 'dgms_notification', 'Appoints the officers empowered to impose penalties under the OSH&WC Code 2020 in the case of mines, specifying the areas each officer covers.', 'S.O. 2504(E)', 'Ministry of Labour & Employment', '2026-05-13', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions Code, 2020.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification05_16072026.pdf', 'GazetteNotification05_16072026.pdf', 2, 320, true, false, 749, 'https://docs.mangalamcoal.com/regs/so-2504-2026-penalty-imposing-officers.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;
insert into regulations (slug, title, category, summary, doc_number, authority, issued_date, status, status_note, source_url, source_filename, relevance, sort_order, published, featured, file_size_kb, download_url) values ('so-2516-2026-eight-hour-shift-belowground', 'S.O. 2516(E) — Maximum eight-hour shift for persons employed belowground', 'dgms_notification', 'Under section 25(1) of the OSH&WC Code 2020, the Central Government notifies that persons employed in belowground workings of a mine shall not work more than eight hours in any shift in a day.', 'S.O. 2516(E)', 'Ministry of Labour & Employment', '2026-05-13', 'in_force', 'Made under the Occupational Safety, Health and Working Conditions Code, 2020.', 'https://www.dgms.gov.in/writereaddata/UploadFile/GazetteNotification08_16072026.pdf', 'GazetteNotification08_16072026.pdf', 2, 320, true, false, 461, 'https://docs.mangalamcoal.com/regs/so-2516-2026-eight-hour-shift-belowground.pdf')
  on conflict (slug) do update set title = excluded.title, category = excluded.category, summary = excluded.summary, doc_number = excluded.doc_number, authority = excluded.authority, issued_date = excluded.issued_date, status = excluded.status, status_note = excluded.status_note, source_url = excluded.source_url, source_filename = excluded.source_filename, relevance = excluded.relevance, sort_order = excluded.sort_order, published = excluded.published, featured = excluded.featured, file_size_kb = excluded.file_size_kb, download_url = excluded.download_url;

-- de-duplicate the OSH&WC (Central) Rules 2026 (same instrument catalogued twice):
-- enrich the canonical row, retire the DGMS-copy duplicate.
update regulations set
     doc_number = 'G.S.R. 345(E)',
     issued_date = '2026-05-08',
     status_note = 'Notified 8 May 2026 under Sections 133-134 of the OSH&WC Code 2020. Supersedes the Mines Rules 1955, Mines Rescue Rules 1985 and Mines Vocational Training Rules 1966, among others.',
     summary = 'The final Central Rules under the OSH&WC Code 2020, notified as G.S.R. 345(E) on 8 May 2026. For mines the Central Government is the appropriate Government, so these Rules apply directly. They prescribe working conditions, welfare facilities, safety committees, health and working-hours requirements and employer duties, and supersede a long list of earlier rules including the Mines Rules 1955, the Mines Rescue Rules 1985 and the Mines Vocational Training Rules 1966.'
   where slug = 'oshwc-code-central-rules-2026';
update regulations set published = false, status_note = 'Duplicate of oshwc-code-central-rules-2026 (same instrument, DGMS copy) — unpublished to avoid a double entry.' where slug = 'osh-wc-central-rules-2026-dgms-copy-12-05-2026';

-- normalise DD-MM-YYYY dates to ISO so they sort correctly
update regulations
     set issued_date = substring(issued_date from 7 for 4) || '-' || substring(issued_date from 4 for 2) || '-' || substring(issued_date from 1 for 2)
   where issued_date ~ '^\d{2}-\d{2}-\d{4}$';
commit;
