// Bilingual UI strings. Hindi is a real second version of the core pages, not a
// machine translation of the whole site: the document-heavy sections (the
// regulations library, the Learn explainers, the press page) stay in English
// because their source material is English, and the nav links straight to them.
export type Lang = 'en' | 'hi';

/** Pages that exist in both languages. '' is the home page. */
export const TRANSLATED = ['', 'about', 'operations', 'safety', 'cares', 'careers', 'contact'] as const;

export const detectLang = (pathname: string): Lang =>
  pathname === '/hi' || pathname.startsWith('/hi/') ? 'hi' : 'en';

/**
 * Whether this page genuinely exists in the other language. The nav toggle can
 * fall back to the other language's home, but an hreflang tag must not: claiming
 * the Hindi equivalent of /news is the Hindi home page is simply false, and the
 * pairing is not reciprocal, so search engines discard it either way.
 */
export function hasAlt(pathname: string, lang: Lang): boolean {
  const slug = (lang === 'hi' ? pathname.replace(/^\/hi\/?/, '') : pathname.replace(/^\//, '')).replace(/\/$/, '');
  return (TRANSLATED as readonly string[]).includes(slug);
}

/** The same page in the other language, falling back to that language's home. */
export function altHref(pathname: string, lang: Lang): string {
  const slug = (lang === 'hi' ? pathname.replace(/^\/hi\/?/, '') : pathname.replace(/^\//, '')).replace(/\/$/, '');
  const has = (TRANSLATED as readonly string[]).includes(slug);
  if (lang === 'hi') return has ? (slug ? `/${slug}` : '/') : '/';
  return has ? (slug ? `/hi/${slug}` : '/hi') : '/hi';
}

export const NAV: Record<Lang, { href: string; label: string }[]> = {
  en: [
    { href: '/about', label: 'About' },
    { href: '/operations', label: 'Operations' },
    { href: '/safety', label: 'Safety' },
    { href: '/learn', label: 'Learn' },
    { href: '/regulations', label: 'Regulations' },
    { href: '/cares', label: 'Cares' },
    { href: '/news', label: 'News' },
    { href: '/careers', label: 'Careers' },
    { href: '/contact', label: 'Contact' },
  ],
  hi: [
    { href: '/hi/about', label: 'हमारे बारे में' },
    { href: '/hi/operations', label: 'संचालन' },
    { href: '/hi/safety', label: 'सुरक्षा' },
    { href: '/learn', label: 'जानकारी' },
    { href: '/regulations', label: 'विनियम' },
    { href: '/hi/cares', label: 'मंगलम केयर्स' },
    { href: '/news', label: 'समाचार' },
    { href: '/hi/careers', label: 'करियर' },
    { href: '/hi/contact', label: 'संपर्क' },
  ],
};

export const UI = {
  en: {
    toggle: 'हिन्दी',
    toggleAria: 'Switch to Hindi',
    portal: 'Operations Portal',
    mail: 'Employee Mail',
    englishOnlyNote: '',
    skip: 'Skip to content',
    navPrimary: 'Primary',
    navMobile: 'Mobile',
    menu: 'Menu',
    close: 'Close',
    askName: 'Ask Mangalam',
    askTag: 'Our coal-mining knowledge, completely open to you',
    askHello: 'Hi — I can answer questions about Mangalam Coalfield and Indian coal mining using information from this site. I can’t make commitments on the company’s behalf. For enquiries, please use the <a href="/contact">contact form</a>.',
    askPlaceholder: 'Ask about operations, safety, careers…',
    askQuestion: 'Your question',
    askSend: 'Send',
    askFoot: 'Answers are generated by Google’s Gemini from this site’s content — please don’t type personal details. For anything official, <a href="/contact">get in touch</a>. <a href="/privacy">Privacy</a>',
    askUnavailable: 'Ask Mangalam is currently unavailable. Please use the contact form.',
    askTooFast: 'You’re sending messages a little fast — please wait a moment and try again.',
    askNoAnswer: 'Sorry — I couldn’t answer that. Please try the contact form.',
    askNoReach: 'Sorry — I couldn’t reach the assistant. Please try again later.',
  },
  hi: {
    toggle: 'English',
    toggleAria: 'Switch to English',
    portal: 'ऑपरेशंस पोर्टल',
    mail: 'कर्मचारी मेल',
    englishOnlyNote: 'विनियम पुस्तकालय, जानकारी लेख और समाचार अनुभाग अंग्रेज़ी में हैं, क्योंकि उनके मूल दस्तावेज़ अंग्रेज़ी में हैं।',
    skip: 'मुख्य सामग्री पर जाएँ',
    navPrimary: 'मुख्य नेविगेशन',
    navMobile: 'मोबाइल नेविगेशन',
    menu: 'मेनू',
    close: 'बंद करें',
    askName: 'मंगलम से पूछें',
    askTag: 'कोयला खनन की हमारी जानकारी, सबके लिए खुली',
    askHello: 'नमस्ते — इस साइट की जानकारी के आधार पर मैं मंगलम कोलफील्ड और भारतीय कोयला खनन से जुड़े सवालों के जवाब दे सकता हूँ। मैं कंपनी की ओर से कोई वादा नहीं कर सकता। पूछताछ के लिए कृपया <a href="/hi/contact">संपर्क फ़ॉर्म</a> का उपयोग करें।',
    askPlaceholder: 'संचालन, सुरक्षा, करियर के बारे में पूछें…',
    askQuestion: 'आपका प्रश्न',
    askSend: 'भेजें',
    askFoot: 'उत्तर Google Gemini द्वारा इस साइट की सामग्री से तैयार किए जाते हैं — कृपया कोई निजी जानकारी न लिखें। किसी भी आधिकारिक विषय के लिए <a href="/hi/contact">संपर्क करें</a>। <a href="/privacy">गोपनीयता</a>',
    askUnavailable: 'मंगलम से पूछें अभी उपलब्ध नहीं है। कृपया संपर्क फ़ॉर्म का उपयोग करें।',
    askTooFast: 'आप बहुत जल्दी-जल्दी संदेश भेज रहे हैं — कृपया थोड़ा रुककर फिर कोशिश करें।',
    askNoAnswer: 'क्षमा करें — मैं इसका उत्तर नहीं दे सका। कृपया संपर्क फ़ॉर्म आज़माएँ।',
    askNoReach: 'क्षमा करें — सहायक से संपर्क नहीं हो सका। कृपया बाद में फिर कोशिश करें।',
  },
} satisfies Record<Lang, Record<string, string>>;
